name: Tom's Yard Screenprint
layout_spectrum: 0.25164413349334114
typography_spectrum: 0.8885133535229591
cta: {}
analytics: {}
opengraph: {}
color:
  brandColors:
    - '#B4AF91'
    - '#787746'
    - '#40411E'
    - '#32331D'
    - '#C03000'
  brandStrength: 0.30515188474097465
  lightness: 0.8134469360794577
  saturation: 0.9977119487784987
  rhythmicContrast: 0.8466618341952562
purpose:
  - type: contact
    label: Cell  +4407542692639
    url: 'tel:+4407542692639'
title: Tom's Yard Screenprint
description: '@ Higher Bussow Farm Studios'
author:
  name: Graham Pullen
  email: no2tomsyard@yahoo.co.uk
navigation:
  - name: Workshops
    id: af5baa17-a63d-4635-8899-051cdd0b6cb0
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/072ad6d7c795ffa91cf2fa541df6c2bb99f59902.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/072ad6d7c795ffa91cf2fa541df6c2bb99f59902.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: .s3-us-west-2.amazonaws.com
        domain: s3-us-west-2.amazonaws.com
        url: 'https://s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
