name: Tom's Yard Screenprint
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24980949447490275
title: Tom's Yard now at Higher Bussow Farm Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#09a6e9'
    - '#6f423f'
    - '#175a51'
    - '#c9c085'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
