name: "Tom's Yard Screenprint"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24980949447490275
title: "Tom's Yard now at Bussow Studios"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#895701'
    - '#cdc793'
    - '#89979a'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
